version: '3'

services:
  ipfs_node:
    image: ipfs/go-ipfs
    ports:
      - "4001:4001"  # IPFS Swarm Port
      - "5001:5001"  # IPFS API Port
      - "8080:8080"  # IPFS Gateway Port
    volumes:
      - ./:/data/ipfs
      - ./:/export 
    command: ["daemon", "--migrate=true"]

volumes:
  ipfs_data:
  exported:


  # sudo docker run -d --name ipfs_host -v $PWD:/export -v $PWD:/data/ipfs -p 4001:4001 
  # -p 4001:4001/udp -p 127.0.0.1:8080:8080 -p 127.0.0.1:5001:5001 ipfs/kubo